"""English interface text. Keys mirror strings_zh.py one to one (tests/test_i18n.py checks)."""

EN: dict[str, str] = {
    # ---------- general ----------
    "app.name": "Personal Board",
    "sep": ", ",
    "paren": " ({x})",
    "zones.join": " = ",
    "weekdays": "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
    "day.label": "{wd} {md}",
    "mode.main": "Main",
    "mode.sample": "Example",
    "mode.practice": "Practice",
    "mode.suffix.sample": " · Example",
    "mode.suffix.practice": " · Practice",

    # ---------- config ----------
    "cfg.missing": "The board is not set up yet: run ./board init first ({path} not found)",
    "cfg.not_json": "{path} is not valid JSON: {error}",
    "cfg.not_object": "The config must be a JSON object",
    "cfg.bad_lang": "lang must be zh or en, got {value!r}",
    "cfg.bad_person": "The config lacks person.id (your id)",
    "cfg.bad_letter": "person.letter must be one capital letter other than G (team-board numbers) and E (example numbers), got {value!r}",
    "cfg.bad_port": "port must be a number",
    "cfg.bad_zone": "{key} is not a valid IANA time zone: {value!r} (e.g. America/Los_Angeles)",
    "cfg.bad_names": "{key} needs at least one item; names must be non-empty and unique",
    "cfg.bad_team": "team_board must be an object whose base_url starts with http:// or https:// (leave it empty to work without a team board)",

    # ---------- entry kinds, sync states ----------
    "kind.start": "Start",
    "kind.result": "Result",
    "kind.wrap": "Wrap-up",
    "kind.note": "Note",
    "kind.digest": "Digest",
    "kind.stage_start": "Stage started",
    "kind.stage_end": "Stage ended",
    "kind.goal_create": "Created",
    "kind.due": "Plan changed",
    "kind.complete": "Completed",
    "kind.abandon": "Abandoned",
    "kind.point_done": "Done",
    "kind.release": "Version closed",
    "kind.summary": "Summary edited",
    "sync.pending": "Unpushed",
    "sync.pushed": "Pushed",
    "sync.skip": "Not pushed",
    "abandon.default": "Abandoned",
    "label.what": "What",
    "label.done_what": "Done",
    "stage.open": "in progress",
    "stage.ended": "ended {at}",
    "stage.none": "No stage",

    # ---------- time ----------
    "time.no_offset": "The time has no UTC offset: {value} (e.g. 2026-10-02T09:30:00-07:00)",
    "time.naive": "Refusing to store a time without a time zone",
    "late.hours": "{n} h",
    "late.days": "{n} d",
    "late.under_hour": "under 1 h",

    # ---------- point tasks ----------
    "point.bad_zone": "point_zone must be one of {options} (or main / second), got {value}",
    "point.repeat_none": "no repeat",
    "point.repeat_monthly": "every month",
    "point.repeat_monthly_desc": "Same day and time every month (on the wall clock of point_zone)",
    "point.bad_repeat": "repeat must be monthly or empty, got {value}",
    "point.bad_at": "point_at must look like 2026-11-01 10:00 (on the wall clock of point_zone) or be an ISO time with an offset, got {value}",
    "point.rule_monthly": "Monthly on day {day}, {time}{zone}",
    "point.rule_once": "Once · {at}{zone}",
    "point.rule_from": "{rule}, from {start}",
    "point.no_push": "Point tasks are not pushed to the team board (it only tracks goals that make progress)",
    "due.overdue": "{late} overdue",
    "due.overdue_say": "\"{title}\" was due {when} and is {late} overdue. Tell me once it is done.",
    "due.today": "due today",
    "due.today_say": "Due today — {title}: {when}. Tell me once it is done.",
    "occ.done": "Done {at}",
    "occ.done_late": ", {late} overdue",
    "occ.overdue": "{late} overdue, not done",
    "occ.upcoming": "Upcoming",
    "occ.cancelled": "Not done before it was cancelled",

    # ---------- action reference ----------
    "act.common.occurred_at": "When it happened: ISO with an offset (e.g. 2026-10-02T09:30:00-07:00); empty = now",
    "act.common.task": "Which piece of work: the name of what this conversation is doing (e.g. \"Onboarding build\")",
    "act.common.tool": "claude / codex / web",
    "act.goal_create": "Create a goal. It gets a birth number on the spot (your letter + a sequence, e.g. {letter}19; it never changes and is never reused). "
                       "`line` is one of the configured lines. On a team line the goal is marked \"unpushed\" and gets created on the team board at wrap-up "
                       "(create with source = the birth number); after the push, use goal_update gnum to switch the display number to the team board's G number — "
                       "the birth number stays and still finds the goal. Personal lines are never pushed, and with no team board connected nothing is marked. "
                       "`parent_gnum` is the goal this one is split from (G number or birth number). "
                       "`due` is the planned finish ({zone}): 2026-10-02 or 2026-10-02 08:00. Ask for it separately when creating and suggest a date; leave it empty only if the human says it cannot be set yet. "
                       "Point task (done once at a moment, e.g. \"pay contractors on the 1st\"): give `point_at` (the first moment, 2026-11-01 10:00), "
                       "`point_zone` (whose wall clock rules — see the value table; default = the main zone) and `repeat=monthly` if it recurs. "
                       "A point task is never pushed, has no stages and no due; the timeline shows one hollow dot when it reaches the moment. "
                       "`what` is the goal's \"What\" (shown under the title; it becomes the note of the team-board create; max 500 characters). You decide whether to write it, without asking: "
                       "leave it empty when someone uninvolved can tell from the title what is to be achieved and when it counts as done (always empty for point tasks); "
                       "otherwise write one or two sentences — the outcome and how to tell it is reached (a checkable criterion, not the implementation).",
    "act.goal_update": "Change a goal's title, next step, blocker, version name, G number (the display number; the birth number cannot change), planned finish, line, parent or status. "
                       "Changing `due` logs a \"plan changed\" entry (unpushed on a team line). "
                       "Point task: `point_at` is the next occurrence after the change (later than now; earlier ones stay as they were and what was done stays done); "
                       "`point_zone` / `repeat` may change with it (`repeat=none` makes it a one-off); a note is logged. Cancel with status=abandoned: no more dots, and it cannot be un-cancelled (create a new one). "
                       "`what` / `done_what` edit the \"What\" / \"Done\" text (only when the human asks; an empty string clears it): `done_what` only on a completed goal — "
                       "a long-running row writes it per version (release). For a goal already on the team board this logs one \"summary edited\" entry (unpushed), pushed at wrap-up as the team board's edit_goal. "
                       "When abandoning, `reason` says why in one sentence; the detail page shows it where \"Done\" would be.",
    "act.log": "Log an entry: kind=start / result (a visible result) / wrap (wrapping up) / note / digest (a lesson or rule written into a handbook or knowledge base; "
               "write \"Handbook x.y.z: what was added\"). `stage` is one of the configured stages or empty (no stage). "
               "On a long-running handbook row a digest may carry `version` (e.g. Handbook 1.5.14): the version badge changes to it and the entry becomes one version in the detail page's changelog.",
    "act.stage_start": "Start a stage (several stages may run at once). Rejected if that stage is already open.",
    "act.stage_end": "End a stage that is open.",
    "act.complete": "Complete a goal (the outcome is verified); stages still open end with it. `done_what` is the \"Done\" text (max 1000 characters; it replaces \"Next\" on the detail page "
                    "and goes along when pushed). You decide whether to write it, without asking: write it like an app's \"What's new\" — short, plain words about the changes a user can see, as many lines as needed, "
                    "no process, reviews, test counts or commit ids. Leave it empty when the title says it all.",
    "act.release": "Close a version of a long-running row (logged when the human accepts the round and the badge changes): `version` is the new badge (e.g. v1.4) — the badge changes with it, no goal_update version_name needed; "
                   "`text` says what this version did (written like complete's done_what); the detail page lists versions in its changelog, highest first. Long-running rows only; never pushed. "
                   "The badge is always the highest-numbered version: a lower one closed later or an old one backfilled does not take it back, nor does voiding this entry — use goal_update version_name to change the badge by hand.",
    "act.point_done": "A point task done once: the hollow dot turns solid. Log this when the human says \"Y is done\". `occurrence` is which one (its moment, written like point_at, "
                      "on the task's own wall clock); empty = the earliest one not done yet (it must be within 7 days — earlier than that is probably a slip, so ask). "
                      "A one-off is complete once ticked. Ticked by mistake: void the entry and the dot is hollow again.",
    "act.point_reminded": "Record that point tasks were already mentioned today. When work starts and the board state's points_due has items due today or overdue "
                          "and reminded_today is false, mention them in one line, then log this; other conversations see true and stay quiet (once a day).",
    "act.todo_add": "Add a to-do, optionally under a goal.",
    "act.todo_done": "Mark a to-do done.",
    "act.note_add": "Save a dictation from the page's dictation box (used by the page).",
    "act.note_resolve": "Mark a dictation as handled once the AI has logged it, with one sentence on what was logged.",
    "act.sync_mark": "Mark entries as pushed to the team board (status=pushed) or not to be pushed (skip). `entry_ids` is a list of entry ids; `team_ref` is the event id the team board returned.",
    "act.void": "Void an entry logged by mistake (it stays on record; nothing is deleted).",

    # ---------- write errors ----------
    "err.int": "{key} must be a numeric id, got {value}",
    "err.no_goal": "No such goal: {key} (use a G number, a birth number such as {example}, or an id)",
    "err.bad_time": "Bad time: {error}",
    "err.future": "The time is in the future: {value}",
    "err.stage_required": "A stage is required: {stages}",
    "err.bad_stage": "stage must be one of {stages}, got {value}",
    "err.bad_due": "due must look like 2026-10-02 or 2026-10-02 08:00 ({zone}), got {value}",
    "err.bad_tool": "tool must be one of {tools}, got {value}",
    "err.summary_long": "\"{label}\" is limited to {max} characters (got {n}): like a \"What's new\", only the changes a user can see",
    "err.need_version": "A version is required (e.g. v1.4, Handbook 1.5.14)",
    "err.not_long_term": "{gnum} is not a long-running row: closing a version is for long-running rows; finish an ordinary goal with complete and done_what",
    "err.version_closed": "{version} of {gnum} is already closed; to change its text, void that entry and log it again",
    "err.before_create": "The time cannot be earlier than the goal's creation ({created})",
    "err.no_action": "No such action: {action} (available: {actions})",
    "err.internal_sync": "_sync is an internal parameter and is not accepted",
    "err.missing": "{action} is missing required fields: {keys}",
    "err.unknown": "{action} does not know these parameters: {keys}",
    "err.conflict": "The board refused the write (it conflicts with existing data — another conversation may have written the same thing): {error}; read the current state and try again",
    "err.bad_line": "line must be one of {lines}, got {value}",
    "err.exists": "{gnum} already exists",
    "err.point_needs_at": "A point task needs point_at (its first moment); for an ordinary goal leave out point_zone / repeat",
    "err.point_no_due": "A point task takes no due or long_term: its moment is its plan, and past it the task is overdue",
    "err.point_no_what": "A point task has no \"What\": the title is the thing to do",
    "err.point_what": "{gnum} is a point task and has no \"What\"",
    "err.done_what_long_term": "{gnum} is a long-running row: \"Done\" is written per version — use release",
    "err.done_what_not_done": "{gnum} is not completed yet: write \"Done\" with complete; the reason for abandoning goes in reason with status=abandoned",
    "err.self_parent": "A goal cannot be its own parent",
    "err.point_status": "{gnum} is a point task: once cancelled it stays cancelled — create a new one to do it again; if it was ticked by mistake, void that \"Done\" entry",
    "err.use_complete": "Use complete to finish a goal (it ends the open stages and logs \"Completed\")",
    "err.bad_status": "status must be active or abandoned (use complete to finish)",
    "err.abandon_before_stage": "The abandon time is earlier than the start of the {stage} stage",
    "err.point_due": "{gnum} is a point task and has no planned finish; change its moment with point_at",
    "err.not_point": "{gnum} is not a point task and has no moment to change",
    "err.point_closed_done": "{gnum} is already done; its moment can no longer change",
    "err.point_closed_cancelled": "{gnum} is cancelled; its moment can no longer change",
    "err.point_at_required": "Changing a point task's rule needs point_at: the next occurrence after the change (later than now)",
    "err.point_at_future": "point_at must be the next occurrence after the change, later than now (got {at}); earlier occurrences stay as they were",
    "err.nothing": "Nothing to change",
    "err.bad_kind": "kind must be start / result / wrap / note / digest",
    "err.version_digest_only": "version only goes with a digest (kind=digest); close a version of a tool row with release",
    "err.not_active": "{gnum} is no longer in progress",
    "err.point_no_stage": "{gnum} is a point task: it has one moment and no stages",
    "err.stage_on_done": "{gnum} is completed; no more stages can be started",
    "err.stage_on_abandoned": "{gnum} is abandoned; no more stages can be started",
    "err.stage_open": "The {stage} stage of {gnum} is already in progress (since {since})",
    "err.stage_not_open": "The {stage} stage of {gnum} is not in progress",
    "err.end_before_start": "The end cannot be earlier than the start of the stage",
    "err.point_complete": "{gnum} is a point task: tick an occurrence with point_done; to stop doing it use goal_update status=abandoned",
    "err.already_done": "{gnum} is already completed",
    "err.complete_before_stage": "The completion time is earlier than the start of the {stage} stage",
    "err.todo": "To-do {id} does not exist or is already done",
    "err.note": "Dictation #{id} does not exist or is already handled",
    "err.bad_sync_status": "status must be pushed or skip",
    "err.bad_entry_ids": "entry_ids must be a list of entry ids, got {value}",
    "err.not_pending": "Entry {id} is not waiting to be pushed",
    "err.void": "Entry {id} does not exist or is already voided",
    "err.not_point_done": "{gnum} is not a point task (finish an ordinary goal with complete)",
    "err.point_cancelled": "{gnum} is cancelled",
    "err.no_occurrence": "{gnum} has no occurrence at {at} (rule: {rule})",
    "err.none_within": "{gnum} has nothing left to do within the next 7 days (rule: {rule}); to tick a later one early, give occurrence",
    "err.already_ticked": "The occurrence at {at} is already ticked (entry {id})",
    "err.just_ticked": "The occurrence at {at} was just ticked by another conversation",
    "err.day_range": "The date range must be in order and at most 93 days",
    "err.act_shape": "action must be a string and params an object",
    "err.request_id": "request_id must be a unique id of 16–128 characters (a UUID is fine); keep it the same when retrying",
    "err.request_reused": "This request_id was used for a different action; read the current state — a retry cannot change its content",

    # ---------- text written into entries ----------
    "text.create": "Created: {title}",
    "text.stage_start": "{stage} stage started",
    "text.stage_end": "{stage} stage ended",
    "text.stage_end_abandon": "{stage} stage ended with the goal abandoned",
    "text.stage_end_complete": "{stage} stage ended with the goal completed",
    "text.complete": "Completed",
    "text.due": "Planned finish {old} → {new}",
    "text.unset": "not set",
    "text.reason": ": {reason}",
    "text.point_change": "Moment changed: {before} → {after}",
    "text.summary_edit": "Edited \"{label}\": {value}",
    "text.cleared": "(cleared)",
    "text.semi": "; ",
    "text.point_done": "Done: {title} (the one at {at})",

    # ---------- team board ----------
    "team.status.active": "In progress",
    "team.status.done": "Done",
    "team.status.abandoned": "Abandoned",
    "team.off": "No team board is connected (team_board.base_url is empty in the config); the personal board works on its own — nothing to pull or push",
    "team.demo": "This is demo data, so team goals are not pulled; start your own board first (./board reset --execute)",
    "team.bad_url": "The team-board address must start with http:// or https://",
    "team.http": "The team board answered {code}: {body}",
    "team.unreachable": "Cannot reach the team board at {base}: {reason}",
    "team.read_error": "Error reading the team board: {error}",
    "team.not_json": "The team board did not return JSON (a login page, perhaps): {head}",
    "team.no_goals": "The team board's answer has no goals",
    "team.write_failed": "Writing to the local board failed: {error}",
    "team.task": "Team board",
    "team.created": "Created (on the team board; backfilled by the pull)",
    "team.created_guess": "Created (on the team board; backfilled by the pull — the team board has the exact time)",
    "team.stage_open": "{stage} stage is in progress on the team board",
    "team.start_at_pull": " (the team board has the real start; logged at pull time)",
    "team.stage_closed": "{stage} stage has ended on the team board",
    "team.at_pull": " (logged at pull time)",
    "team.marked": "Marked {status} on the team board",
    "team.marked_stage": "{marked}; {stage} stage ended",
    "team.paused": "Paused: {kind}",
    "team.note_paused": "Team board: {text}",
    "team.note_resumed": "Team board: resumed",
    "team.due": "Planned finish changed on the team board to {new} (was {old})",
    "team.no_due": "none",
    "team.reopened": "Reopened on the team board (back in progress)",
    "team.not_mine": "Team board: no longer mine",
    "team.not_mine_note": "On the team board this goal is no longer mine (or was deleted). To close it here use complete / void; to keep it, fix the owner there and pull again",
    "head.pulled_ago": "Team goals pulled {mins} min ago",
    "head.pulled_at": "Team goals pulled {at}",
    "head.never_pulled": "Team goals never pulled",

    # ---------- hypothetical cases on the example board ----------
    "sample.task": "Example",
    "sample.e1.title": "Pet-sitting bookings (hypothetical)",
    "sample.e1.next": "Hypothetical: what a bigger piece of work looks like when each block has one owner end to end",
    "sample.e11.title": "A Booking screens",
    "sample.e11.next": "Depends on no other block; runs from product straight through to test",
    "sample.e12.title": "B Orders & scheduling",
    "sample.e12.next": "The whole build comes after C (the sitter-shop API, someone else's block) is done",
    "sample.e12.log_wait": "Product done; waiting on C (the shop API, someone else's block) — waiting on a dependency is not build time",
    "sample.e12.log_go": "C is done; build started",
    "sample.e11.log_back": "Testing found 5 issues; back to product to fix them while testing continues",
    "sample.e2.title": "In-app message centre (hypothetical)",
    "sample.e2.next": "Parent goal: start it, do the business stage, sign off, catch what falls through. Three blocks go to others (on the team board). Checkpoint: I review once the product spec is done",
    "sample.e2.log": "Business brief handed over; the three blocks are created on the team board",
    "sample.e2.todo": "Review the product spec when it is done, then decide who builds it",

    # ---------- demo data ----------
    "seed.bad_lang": "Demo data comes in zh and en only",
    "seed.not_empty": "The board already holds data; demo data only goes into an empty board (to start over: ./board reset --execute)",

    # ---------- HTTP API ----------
    "http.no_page": "No such page: {path}",
    "http.no_api": "No such endpoint",
    "http.bad_params": "Bad parameters: {error}",
    "http.bad_length": "Content-Length is not a number",
    "http.not_json": "The request body is not JSON",
    "http.sample_readonly": "The example board is read-only; try things on the practice board",
    "http.act_format": 'Format: {"action": "...", "params": {...}}',
    "http.mode_no_pull": "Only the main board pulls team goals",
    "http.reset_practice_only": "Only the practice board can be reset",

    # ---------- command line ----------
    "cli.serving": "Personal Board: http://127.0.0.1:{port}/ (example /sample/, practice /practice/)",
    "cli.init_exists": "Already set up: {path}. Add --force to write a fresh config (the database is not touched).",
    "cli.init_done": "Set up: {path}\n  You are {name} (id {id}, birth letter {letter}), port {port}, time zone {zones}\n  Team board: {team}\n  Database {db}; practice database built\nNext: ./board seed (optional demo data) → ./board start",
    "cli.team_off": "not connected (standalone)",
    "cli.seed_done": "Demo data written to {db}: {goals} goals, {entries} entries; the practice database was rebuilt with it.\nDone looking? Start your own: ./board reset --execute",
    "cli.practice_dry": "DRY RUN: would rebuild the practice database from the main data as it is now + the hypothetical cases. Add --execute to do it.",
    "cli.practice_done": "Practice database rebuilt: {path}",
    "cli.already_running": "Already running (pid {pid}): http://127.0.0.1:{port}/",
    "cli.started": "Started (pid {pid}): http://127.0.0.1:{port}/  example /sample/  practice /practice/  log {log}",
    "cli.start_failed_exited": "Did not start (the process exited — the port may be taken); see the log: {log}",
    "cli.start_failed_silent": "Did not start (the process is not answering); see the log: {log}",
    "cli.not_running": "Not running",
    "cli.stopped": "Stopped (pid {pid})",
    "cli.status_running": "Running, pid {pid}  http://127.0.0.1:{port}/  data {data}",
    "cli.status_stopped": "Not running  http://127.0.0.1:{port}/  data {data}",
    "cli.app_macos_only": "The app launcher exists for macOS only",
    "cli.app_foreign": "{path} already exists and was not created by this tool; it will not be overwritten. Rename or move it first.",
    "cli.app_dry": "DRY RUN: would create {path} (double-click = start the server and open the board). Add --execute to do it.",
    "cli.app_alert": "Personal Board did not start. See the log:",
    "cli.app_done": "Created: {path}\n  Double-click opens {url}\n  Drag it to the Dock if you like; log {log}",
    "cli.reset_dry": "DRY RUN: would back {db} up to {backups}/, then empty and recreate it ({name} stays the owner) and rebuild the practice database. Add --execute to do it.",
    "cli.reset_done": "Emptied: {db}; backup {backup}; practice database rebuilt.",
    "cli.no_backup": "none (there was no main database)",
    "cli.backup_dry": "DRY RUN: would back {db} up online, check its integrity and keep the latest 30. Add --execute to do it.",
    "cli.backup_bad": "The backup failed its integrity check",

    # ---------- MCP ----------
    "mcp.now": "now",
    "mcp.bad_when": "when must look like 2026-10-02 09:30 (read in `zone`) or be an ISO time with an offset",
    "mcp.unknown_args": "{tool} does not know these arguments: {keys}",
    "mcp.missing_args": "{tool} is missing arguments: {keys}",
    "mcp.bad_type": "{key} of {tool} has the wrong type; expected {type}",
    "mcp.no_tool": "No such tool: {name}",
    "mcp.no_guide": "The guide is missing: {path} (the MCP instructions come from it; the server will not start without it)",
    "mcp.bad_method": "Unsupported method: {method}",
    "mcp.actions_note": "Entries (log / stage_start / stage_end) carry task and tool; occurred_at empty = now",
    "mcp.pending_note": "At wrap-up show this list to the human for a nod, push each entry through the team board's own MCP, then mark it with sync_mark",
    "mcp.state": "The board right now: header (unpushed count, when team goals were last pulled), goals in progress per line (number, open stages, next step, last entry), "
                 "one day's entries by hour, the last 7 days, to-dos, dictations, and point tasks due today or overdue (points_due). day empty = today. Read-only.",
    "mcp.goal": "One goal in detail: each stage's start, end and duration, all entries by day, to-dos, related conversations, its parent and its blocks. Read-only.",
    "mcp.timeline": "The goals and stage spans that belong on the timeline for a period (those in progress + those active in the period). Read-only.",
    "mcp.pending": "Every unpushed entry (bound for the team board, not pushed yet): the list to show the human at wrap-up. Empty when no team board is connected. Read-only.",
    "mcp.actions": "The action reference (the single source): what each action does, its required and optional fields, and the value tables for lines, stages, entry kinds, tools and time zones. Read-only.",
    "mcp.guide": "The full guide (filing a conversation at its start, how much to log, stage gates, pushing to the team board at wrap-up, dictation and point tasks). "
                 "Some clients show only the beginning of the MCP instructions, so read this before filing or logging. Read-only.",
    "mcp.time": "Time conversion (done with the time-zone database — do not do it in your head): no `when` gives now; with \"2026-10-02 09:30\" and `zone` it returns the moment in every configured zone, "
                "a one-line version for the human to confirm (both) and a value ready for occurred_at. Read-only.",
    "mcp.act": "Write one action to the board ({actions}). params go to the board's validation as they are and errors come back as they are. Returns ids / goal_id / gnum. Writes.",
    "mcp.pull": "Pull my goals from the team board again (reads the team board, writes goal rows here). Errors out as-is when no team board is connected or the pull fails.",
    "mcp.p.day": "YYYY-MM-DD (a date in the main time zone)",
    "mcp.p.goal": "G number (G2.2) or birth number ({letter}19; still works after the goal is pushed to the team board)",
    "mcp.p.iso": "ISO time with an offset",
    "mcp.p.when": "2026-10-02 09:30 (read in `zone`) or an ISO time with an offset; empty = now",
    "mcp.p.zone": "The zone `when` is read in: main (default) / second, or a configured zone's name or label",
    "mcp.p.request_id": "A UUID is recommended; when the outcome is unclear, retry with the same id and parameters to avoid a duplicate entry",
    "mcp.p.action": "An action name from the action reference (actions)",
    "mcp.p.params": "The action's parameters; add occurred_at (with an offset) when backfilling; entries carry task (what this conversation is doing) and tool (claude / codex)",
    "mcp.check.data": "Data: {db} ({mode}) — {name}, birth letter {letter}",
    "mcp.check.guide": "Guide: {path} (version {version}, {chars} characters)",
    "mcp.check.summary": "{goals} goals in progress; {pending} unpushed; team board: {team}",
    "mcp.check.tools": "Tools: {tools}",

    # ---------- page templates ----------
    "tpl.pending_tip": "Entries bound for the team board that are not pushed yet",
    "tpl.pending_a": "",
    "tpl.pending_b": " unpushed",
    "tpl.pull_tip": "Pull the goals you own from the team board again",
    "tpl.pull": "Pull team goals",
    "tpl.theme_tip": "Light / dark / follow the system",
    "tpl.theme_light": "Light",
    "tpl.theme_dark": "Dark",
    "tpl.theme_auto": "Auto",
    "tpl.guide": "Guide",
    "tpl.zoom_day": "Day",
    "tpl.zoom_three": "3 days",
    "tpl.zoom_week": "Week",
    "tpl.earlier": "Earlier",
    "tpl.later": "Later",
    "tpl.back_today": "Today",
    "tpl.pick_tip": "Open the calendar and jump to a day",
    "tpl.unfold_all": "Expand all",
    "tpl.fold_all": "Collapse all",
    "tpl.goals": "Goals",
    "tpl.hint": "Drag to see other days · click a date for that day's entries · click a line's header to fold it · hover a goal to light it and its blocks · a goal in progress stays from its creation on, dashed beyond now; a finished one drifts out of view and returns when you drag back · a point task (say, a monthly payment) appears only at its moment: hollow = not done, solid = done, overdue stays until today in red",
    "tpl.order_tip": "Order of the day's entries; your choice is remembered",
    "tpl.order_desc": "Newest first",
    "tpl.order_asc": "Chronological",
    "tpl.todos": "To-dos",
    "tpl.dictation": "Dictation",
    "tpl.dictation_help": "Write it down in your own words (dictated or typed). Saving copies a short prompt — paste it into an AI conversation and the AI logs it through the board's API, asking first if anything is missing. Every change goes through here; there are no forms.",
    "tpl.dictation_ph": "For example: onboarding ran end to end today, regression is next. Or: tomorrow, finish the rating-prompt spec first…",
    "tpl.dictation_save": "Save & copy for the AI",
    "tpl.changelog": "Changelog",
    "tpl.stage_spans": "Stages",
    "tpl.entries": "Entries",
    "tpl.tasks": "Related conversations / tasks",

    # ---------- the guide page ----------
    "guide.title": "Guide",
    "guide.subtitle": "Getting started with your personal board",
    "guide.what.h": "What this is",
    "guide.what.body": "<p>The personal board is your own live workbench. Every AI conversation you open (Claude Code, Codex) is filed up front under <b>a line, a goal and a stage</b>; the AI logs an entry for each visible result and one when wrapping up. Open the board and you know where everything on your plate stands and what happened today. The data stays on this computer (sqlite, append-only — nothing is deleted).</p>",
    "guide.start.h": "1. Set up your board (once)",
    "guide.start.body": "<pre>./board init --name \"Your name\" --letter Y\n./board seed        # optional: a fictional demo board to look around in\n./board start\n./board open</pre><p>Lines, stages, time zones and language live in <code>config.json</code> in the data directory; restart after editing. Done with the demo data? <code>./board reset --execute</code> (backs up, then empties). After a reboot just run <code>./board start</code> again.</p>",
    "guide.ai.h": "2. Connect your AI (once)",
    "guide.ai.body": "<p>Claude Code (registered for your user, available in every directory):</p><pre>claude mcp add -s user personal-board -- python3 /your/path/personal-board/cli/mcp.py</pre><p>Codex: add to <code>~/.codex/config.toml</code>:</p><pre>[mcp_servers.personal-board]\ncommand = \"python3\"\nargs = [\"/your/path/personal-board/cli/mcp.py\"]</pre><p>From then on the AI follows the guide that travels with the connection; you do not need to paste anything.</p>",
    "guide.daily.h": "3. Day to day",
    "guide.daily.body": "<ul><li><b>Starting</b>: tell the AI \"let's start\". It reads the board and lists today's goals and their next steps; you pick what comes first.</li><li><b>As you go</b>: work in any conversation; the AI logs the start, the results and the wrap-up by itself, and asks before entering a new stage.</li><li><b>Dictation</b>: to change or add something, write it in the dictation box, save and paste it to the AI. No forms.</li><li><b>Point tasks</b>: things done once at a moment (say, paying contractors on the 1st). One sentence to the AI sets it up; the timeline shows a hollow dot at that moment, solid once you say it is done, and red until today if it is overdue. On the day it is due, the first conversation to start work reminds you once.</li><li><b>Wrapping up</b>: say \"wrap up\". The AI sums up the day; with a team board connected it lists the unpushed entries and pushes them after your nod.</li><li><b>Example / Practice</b>: \"Example\" in the header is a live mirror of your data plus two hypothetical cases (read-only); \"Practice\" is a sandbox you can reset at any time, fully separate from your real data.</li></ul>",
    "guide.team.h": "4. Connect a team board (optional)",
    "guide.team.body": "<p>Not configured means fully off: no pulls, no pushes, nothing about it on the page. To connect, set <code>base_url</code> and <code>token</code> under <code>team_board</code> in <code>config.json</code> (or put the token in the <code>PERSONAL_BOARD_TEAM_TOKEN</code> environment variable). From then on, creations, stage starts and ends, plan changes and completions on team lines are marked \"unpushed\"; at wrap-up you nod and the AI pushes them through the team board's own MCP. Personal lines are never pushed.</p>",

    # ---------- text in the browser (js.*) ----------
    "js.app_name": "Personal Board",
    "js.sep": ", ",
    "js.paren": " ({x})",
    "js.today": "Today",
    "js.wd_mon": "Mon", "js.wd_tue": "Tue", "js.wd_wed": "Wed", "js.wd_thu": "Thu", "js.wd_fri": "Fri", "js.wd_sat": "Sat", "js.wd_sun": "Sun",
    "js.cal_wd": "Mo,Tu,We,Th,Fr,Sa,Su",
    "js.cal_entries": "{n} entries",
    "js.cal_prev": "Previous month",
    "js.cal_next": "Next month",
    "js.cal_month": "{y}-{m}",
    "js.cal_hint": "A dot marks a day with entries",
    "js.st_active": "In progress",
    "js.st_done": "Done",
    "js.st_abandoned": "Abandoned",
    "js.no_stage": "No stage",
    "js.digest": "Digest",
    "js.backfilled": "Backfilled",
    "js.hours": "{n} h",
    "js.late_hours": "{n} h",
    "js.late_days": "{n} d",
    "js.late": "{late} late",
    "js.late_done": "finished {late} late",
    "js.overdue": "{late} overdue",
    "js.overdue_done": "done {late} overdue",
    "js.missed_total": " ({n} missed in all)",
    "js.missed_n": "{n} missed",
    "js.cancelled": "Cancelled",
    "js.occ_done": "Done",
    "js.occ_overdue": "Overdue, not done",
    "js.occ_upcoming": "Upcoming",
    "js.occ_cancelled": "Not done before it was cancelled",
    "js.team_number": "Number on the team board",
    "js.next_is": "Next: {text}",
    "js.unfold_blocks": "Show the blocks below",
    "js.fold_blocks": "Hide the blocks below",
    "js.blocks_folded": "{n} blocks hidden",
    "js.blocks_n": "{n} blocks",
    "js.open_inside": "in progress inside",
    "js.stage_of": "{stage} stage",
    "js.started": "Started {at}",
    "js.plan_at": "Plan {at}",
    "js.moved_to": "Moved to {at}",
    "js.items_folded": "{n} hidden",
    "js.items_n": "{n}",
    "js.none_here": "Nothing in this period",
    "js.moved_notice": "Now at {day}: ",
    "js.rows_in": "{n} active here came in",
    "js.rows_out": "{n} idle here left",
    "js.leg_going": "Still going",
    "js.leg_entry": "Entry",
    "js.leg_point": "Point task, not done",
    "js.pull_failed": "Pulling team goals failed: {error}",
    "js.pull_error": "Pull failed: {error}",
    "js.pulling": "Pulling…",
    "js.mode_sample": "Example board",
    "js.mode_practice": "Practice board",
    "js.note_demo": "Demo data: this is the board of a fictional small team building a pet-care app, here to show what a personal board looks like in use. It lives on this computer only. Ready for your own? Run <code>./board reset --execute</code> in a terminal (it backs up first).",
    "js.note_sample": "Example board: a <b>live mirror</b> of your main board (real goals and entries stay in sync) plus two hypothetical cases that show a bigger piece of work split into blocks. <b>Read-only</b> — try things on the practice board.",
    "js.note_practice": "Practice board: play freely. Entries here are <b>not real</b> and never reach the team board. Made a mess? {button} (back to your main data as it is now + the hypothetical cases). To point an AI at the practice data, start the MCP server with PERSONAL_BOARD_PRACTICE=1.",
    "js.reset_practice": "Reset practice data",
    "js.reset_confirm": "Reset the practice data to your main data as it is now + the hypothetical cases?",
    "js.day_title": "{day} — {n} entries",
    "js.pick_date": "Pick a date",
    "js.no_todos": "No to-dos",
    "js.notes_done": "{n} handled",
    "js.empty_day": "No entries on this day yet. Work in any AI conversation and the AI logs the results here.",
    "js.note_n": "Dictation #{id}",
    "js.note_about": "about {gnum}",
    "js.note_resolved": "handled {at}: {summary}",
    "js.copy_to_ai": "Copy for the AI",
    "js.pending_title": "Entries not pushed to the team board yet ({n})",
    "js.pending_none": "Nothing unpushed",
    "js.pending_help": "At wrap-up tell the AI \"wrap up\": it shows you this list for a nod, then pushes it to the team board.",
    "js.back_to_day": "Back to the day's entries",
    "js.dictation_prompt": "Please log the dictation below on my personal board (dictation #{id}). Follow the personal-board guide: read the board first and match it to a goal and a stage; if anything is missing, ask me instead of guessing; when done, mark dictation #{id} as handled and tell me what you logged.",
    "js.copy_fallback": "The browser blocked the automatic copy: the text below is selected — press ⌘C / Ctrl+C.",
    "js.copied": "Dictation #{id} copied; paste it into an AI conversation.",
    "js.write_first": "Write something first",
    "js.save_failed": "Not saved: {error}",
    "js.long_term": "Long-running",
    "js.pending_n": "{n} unpushed",
    "js.what": "What",
    "js.done_what": "Done",
    "js.why_abandoned": "Why abandoned",
    "js.next": "Next",
    "js.blocker": "Blocker",
    "js.moment": "Moment",
    "js.next_occ": "; next {at}",
    "js.point_note": "; point task, not pushed to the team board",
    "js.point_note_solo": "; point task",
    "js.open_stages": "Open stages",
    "js.source": "Source",
    "js.src_pushed": "Created here, pushed to the team board",
    "js.src_team": "Team board (mine)",
    "js.src_local": "Created here",
    "js.birth": "Birth number",
    "js.birth_pushed": " (shown as {gnum} once pushed to the team board; {birth} finds it on both)",
    "js.birth_note": "; cite it in commit messages",
    "js.created": "Created",
    "js.plan": "plan {due}",
    "js.plan_unset": "no plan set",
    "js.plan_was": " (originally {due})",
    "js.belongs": "Part of",
    "js.blocks": "Blocks",
    "js.block_done": " (done)",
    "js.occurrences": "Occurrences",
    "js.th_moment": "Moment",
    "js.th_done": "Status",
    "js.th_stage": "Stage",
    "js.th_start": "Start",
    "js.th_end": "End",
    "js.th_hours": "Duration",
    "js.no_stages": "No stages",
    "js.no_entries": "No entries yet",
    "js.no_tasks": "No conversation has logged on this goal yet",

    # ---------- case packs ----------
    "case.unreadable": "Cannot read the case pack {path}: {error}",
    "case.bad_format": "Not a personal-board case pack (format must be 1 and tables must be present)",
    "case.bad_rows": "The pack has rows the board cannot take; nothing was written: {error}",
    "case.not_empty": "The board already holds data; a case pack only goes into an empty board (to start over: ./board reset --execute)",
    "case.no_config": "This pack has no lines or stages to adopt; it loads fine without --adopt-config",
    "case.someone": "someone",
    "case.label": "a copy of {who}'s board (exported {at})",
    "case.label_undated": "a copy of {who}'s board",
    "case.no_push": "Case-pack data; never pushed to a team board from here",
    "team.case": "This board holds case-pack data, so team goals are not pulled; start your own board first (./board reset --execute)",
    "cli.case_done": "Loaded {label} into {db}: {goals} goals, {entries} entries, {todos} to-dos; unpushed entries were marked \"not pushed\" and the practice database was rebuilt.\nDone looking? Start your own: ./board reset --execute",
    "cli.case_missing": "Note: the pack uses names your config does not have (lines: {lines}; stages: {stages}); they still display (such lines are listed last). To show them in the pack's own order and colours, reset and load it again with --adopt-config.",
    "cli.case_adopted": "The pack's lines and stages were written to the config.",
    "cli.export_done": "Exported: {path} ({goals} goals, {entries} entries, {todos} to-dos; dictations are left out). Others load it into an empty board with ./board seed --case <this file>.",
    "cli.none": "none",
    "js.note_case": "Case data: this is <b>{label}</b>, here to show a personal board in use. It lives on this computer only and is never pushed to a team board. Ready for your own? Run <code>./board reset --execute</code> in a terminal (it backs up first).",
}
