"""中文界面文字。键与 strings_en.py 一一对应（tests/test_i18n.py 会核对）。"""

ZH: dict[str, str] = {
    # ---------- 通用 ----------
    "app.name": "个人看板",
    "sep": "、",
    "paren": "（{x}）",
    "zones.join": "= ",
    "weekdays": "周一,周二,周三,周四,周五,周六,周日",
    "day.label": "{md} {wd}",
    "mode.main": "正式",
    "mode.sample": "示例",
    "mode.practice": "练手",
    "mode.suffix.sample": " · 示例",
    "mode.suffix.practice": " · 练手",

    # ---------- 配置 ----------
    "cfg.missing": "个人看板还没初始化：先运行 ./board init（找不到 {path}）",
    "cfg.not_json": "{path} 不是合法的 JSON：{error}",
    "cfg.not_object": "配置要是一个 JSON 对象",
    "cfg.bad_lang": "lang 只能是 zh 或 en，收到 {value!r}",
    "cfg.bad_person": "配置缺少 person.id（本人的 id）",
    "cfg.bad_letter": "person.letter 要是一个大写字母，且不能是 G（团队看板的号）或 E（示例的号），收到 {value!r}",
    "cfg.bad_port": "port 要是数字",
    "cfg.bad_zone": "{key} 不是有效的 IANA 时区名：{value!r}（例 America/Los_Angeles）",
    "cfg.bad_names": "{key} 至少要有一项，名称不能为空、不能重复",
    "cfg.bad_team": "team_board 要是对象，base_url 以 http:// 或 https:// 开头（不连团队看板就留空）",

    # ---------- 记录种类、推送状态 ----------
    "kind.start": "开工",
    "kind.result": "结果",
    "kind.wrap": "收尾",
    "kind.note": "备注",
    "kind.digest": "沉淀",
    "kind.stage_start": "环节开始",
    "kind.stage_end": "环节结束",
    "kind.goal_create": "立项",
    "kind.due": "改计划日",
    "kind.complete": "完成",
    "kind.abandon": "放弃",
    "kind.point_done": "做完",
    "kind.release": "版本收口",
    "kind.summary": "改概要",
    "sync.pending": "未推",
    "sync.pushed": "已推",
    "sync.skip": "不推",
    "abandon.default": "放弃",
    "label.what": "做什么",
    "label.done_what": "做了什么",
    "stage.open": "进行中",
    "stage.ended": "已结束 {at}",
    "stage.none": "未分环节",

    # ---------- 时间 ----------
    "time.no_offset": "时间缺少时区偏移: {value}（例：2026-10-02T09:30:00-07:00）",
    "time.naive": "拒绝写入没有时区的时间",
    "late.hours": "{n} 小时",
    "late.days": "{n} 天",
    "late.under_hour": "不到 1 小时",

    # ---------- 点状任务 ----------
    "point.bad_zone": "point_zone 只能是 {options}（也可写 main / second），收到 {value}",
    "point.repeat_none": "不重复",
    "point.repeat_monthly": "每月",
    "point.repeat_monthly_desc": "每月同一天同一时刻（按 point_zone 的钟点算）",
    "point.bad_repeat": "repeat 只能是 monthly（每月）或不填，收到 {value}",
    "point.bad_at": "point_at 要写成 2026-11-01 10:00（按 point_zone 的钟点）或带时区的 ISO，收到 {value}",
    "point.rule_monthly": "每月 {day} 号 {time}{zone}",
    "point.rule_once": "一次 · {at}{zone}",
    "point.rule_from": "{rule}，{start}起",
    "point.no_push": "点状任务不推团队看板（团队看板只看有进展的目标）",
    "due.overdue": "过期 {late}",
    "due.overdue_say": "「{title}」{when}那次过期 {late}还没做，做了说一声",
    "due.today": "今天到点",
    "due.today_say": "今天要{title}：{when}，做了说一声",
    "occ.done": "做完 {at}",
    "occ.done_late": "，过期 {late}",
    "occ.overdue": "过期 {late}，还没做",
    "occ.upcoming": "还没到",
    "occ.cancelled": "取消前没做",

    # ---------- 操作说明 ----------
    "act.common.occurred_at": "发生时间，带时区的 ISO（例 2026-10-02T09:30:00-07:00）；不填 = 现在",
    "act.common.task": "来自哪件事：这个对话在做的事的名字（例「引导改版开发」）",
    "act.common.tool": "claude / codex / web",
    "act.goal_create": "在个人看板上立一个目标，立项那一刻发出生号（本人字母＋序号，例 {letter}19；一辈子不变，用过的号不再发）。"
                       "line 填配置里的线之一；属于团队线的会标「未推」，收尾时推到团队看板立项（create 带 source=出生号），"
                       "推完用 goal_update gnum 把显示号换成团队看板给的 G 号，出生号不变、照样能用它找到这个目标。个人线不推；没连团队看板时什么都不标。"
                       "parent_gnum 填从哪个目标拆出来（G 号或出生号都行）。"
                       "due 是计划完成（{zone}），写 2026-10-02 或 2026-10-02 08:00；立项时要单独问一句并附建议值，人说不好定才空着。"
                       "点状任务（只在某个时间点做一次的事，例「每月 1 号给外包结款」）：填 point_at（第一次的时刻，写 2026-11-01 10:00）、"
                       "point_zone（按哪个时区的钟点算，取值见取值表，不填 = 主时区）、每月重复再填 repeat=monthly；"
                       "点状任务不推团队看板、不开环节、不填 due，时间线上到那个时间点才出现一个空心大点。"
                       "what 是「做什么」（详情页标题下显示，推团队看板时就是 create 的 note，500 字以内）：AI 自判写不写、不问人——"
                       "没参与的人只看标题能知道要达成什么、做到什么算完就空着（点状任务一律不写）；不能就写一到两句：要达成什么结果 + 怎么算达成（能验证的判据，不写实现）。",
    "act.goal_update": "改目标的名称、下一步、卡点、版本名、G 号（显示号；出生号改不了）、计划完成日、线、上层或状态。改 due 会记一条「改计划日」（团队线标未推）。"
                       "点状任务改日子：point_at 写改完以后的下一次（要晚于现在；之前的几次照旧，做过的仍算做过），可同时改 point_zone / repeat"
                       "（repeat 填 none 改成只做一次），会记一条备注；取消：status=abandoned，之后不再出点，取消了不再恢复（要再做就新建）。"
                       "what / done_what 改「做什么 / 做了什么」（人说要改才改；填空字符串 = 清空）：done_what 只能写在已完成的目标上，"
                       "长期行的按版本写（release）；目标已经在团队看板上的，会记一条「改概要」（未推），收尾时推团队看板的 edit_goal。"
                       "放弃时 reason 写一句为什么放弃，详情页显示在「做了什么」那一栏。",
    "act.log": "记一条：kind=start（开工）/ result（看得见的结果）/ wrap（收尾）/ note（备注）/ digest（沉淀：经验或规则写进了手册、知识库，文字写「手册 x.y.z：沉淀了什么」）；"
               "stage 填配置里的环节之一或不填（未分环节）。"
               "手册类长期行的沉淀带 version（例 手册 1.5.14）：版本牌一并换成它，这条也是详情页更新日志里的一版。",
    "act.stage_start": "开始一个环节（可以和别的环节同时进行）。同一环节已经在进行中会拒绝。",
    "act.stage_end": "结束一个正在进行的环节。",
    "act.complete": "目标完成（业务验证通过）；还开着的环节一起结束。done_what 是「做了什么」（1000 字以内；详情页「下一步」那栏换成它，"
                    "推团队看板时带上）：AI 自判写不写、不问人——照 App Store 的 What's new 写，用简洁通俗的话概括用的人看得见的变化，条数不限，"
                    "不写过程、审查、测试条数、提交号；完成的东西就是标题本身、没别的可说就空着。",
    "act.release": "长期行一版收口（人认了这一轮、换版本牌那一刻记）：version 是新版本牌（例 v1.4），版本牌一并换掉，不用再 goal_update version_name；"
                   "text 写这版做了什么（写法同 complete 的 done_what），详情页「更新日志」按版本倒序列出。只给长期行用，不推团队看板。"
                   "版本牌永远是号最大的那一版：后收口的小号、补录的旧版都不会把牌换回去；作废这条也不会，要改牌用 goal_update version_name。",
    "act.point_done": "点状任务做完一次：空心点变实心。人说「Y 做了」就记这条。occurrence 是哪一次（那一次的时刻，写法同 point_at，"
                      "按任务自己的钟点）；不填 = 最早一次还没做的（它要在 7 天之内，更早的提前量多半是说错了，先问人）。"
                      "只做一次的任务勾完就算完成。勾错了用 void 作废这条，点变回空心。",
    "act.point_reminded": "记下「今天已经提醒过点状任务」：开工时看板现状的 points_due 有今天到点或已过期没做的、"
                          "且 reminded_today 为 false，就在回复里提一行，然后记这条；当天别的对话看到 true 就不再提（一天只提一次）。",
    "act.todo_add": "加一条待办，可挂在某个目标下。",
    "act.todo_done": "待办完成。",
    "act.note_add": "口述框保存一段原话（页面用）。",
    "act.note_resolve": "AI 处理完一条口述后标记，写一句录了什么。",
    "act.sync_mark": "把记录标成已推到团队看板（status=pushed）或不推（skip）。entry_ids 是记录编号列表；team_ref 写团队看板返回的事件号。",
    "act.void": "作废一条记错的记录（留痕，不删）。",

    # ---------- 写操作的报错 ----------
    "err.int": "{key} 要是数字编号，收到 {value}",
    "err.no_goal": "没有这个目标：{key}（用 G 号、出生号（例 {example}）或编号）",
    "err.bad_time": "发生时间不对：{error}",
    "err.future": "发生时间比现在还晚：{value}",
    "err.stage_required": "要写环节：{stages}",
    "err.bad_stage": "环节只能是 {stages}，收到 {value}",
    "err.bad_due": "due 要写成 2026-10-02 或 2026-10-02 08:00（{zone}），收到 {value}",
    "err.bad_tool": "tool 只能是 {tools}，收到 {value}",
    "err.summary_long": "「{label}」最多 {max} 字（收到 {n} 字）：照 What's new 只写用的人看得见的变化",
    "err.need_version": "要写版本号（例 v1.4、手册 1.5.14）",
    "err.not_long_term": "{gnum} 不是长期行：版本收口只给长期行用；普通目标做完用 complete 带 done_what",
    "err.version_closed": "{gnum} 的 {version} 已经收口过了；要改这版的说明，作废那条再记",
    "err.before_create": "发生时间不能早于目标立项（{created}）",
    "err.no_action": "没有这个操作：{action}（可用：{actions}）",
    "err.internal_sync": "_sync 是内部参数，不接受",
    "err.missing": "{action} 缺必填：{keys}",
    "err.unknown": "{action} 不认识的参数：{keys}",
    "err.conflict": "看板拒绝写入（和已有数据冲突，可能另一个对话同时写了同一处）：{error}；读一下现状再试",
    "err.bad_line": "线只能是 {lines}，收到 {value}",
    "err.exists": "已经有 {gnum} 了",
    "err.point_needs_at": "点状任务要写 point_at（第一次的时刻）；不是点状任务就别填 point_zone / repeat",
    "err.point_no_due": "点状任务不填 due、long_term：时间点就是它的「计划」，过了没做就算过期",
    "err.point_no_what": "点状任务不写「做什么」：标题就是要做的那件事",
    "err.point_what": "{gnum} 是点状任务，不写「做什么」",
    "err.done_what_long_term": "{gnum} 是长期行：「做了什么」按版本写，用 release",
    "err.done_what_not_done": "{gnum} 还没完成：「做了什么」在 complete 时写；放弃的原因写在 status=abandoned 的 reason",
    "err.self_parent": "不能挂在自己下面",
    "err.point_status": "{gnum} 是点状任务：取消了不再恢复，要再做就新建一条；勾错了作废那条「做完」记录",
    "err.use_complete": "标完成请用 complete（它会结束开着的环节并记一条「完成」）",
    "err.bad_status": "status 只能是 active / abandoned（完成用 complete）",
    "err.abandon_before_stage": "放弃时间早于「{stage}」环节的开始",
    "err.point_due": "{gnum} 是点状任务，没有计划完成日；改日子用 point_at",
    "err.not_point": "{gnum} 不是点状任务，没有时间点可改",
    "err.point_closed_done": "{gnum} 已经做完了，不再改时间点",
    "err.point_closed_cancelled": "{gnum} 已经取消了，不再改时间点",
    "err.point_at_required": "改点状任务的规则要写 point_at：改完以后的下一次是什么时候（要晚于现在）",
    "err.point_at_future": "point_at 要写改完以后的下一次、晚于现在（收到 {at}）；之前的几次照旧，做过的仍算做过",
    "err.nothing": "没有要改的东西",
    "err.bad_kind": "kind 只能是 start / result / wrap / note / digest",
    "err.version_digest_only": "version 只跟沉淀（kind=digest）一起写；工具类长期行的版本收口用 release",
    "err.not_active": "{gnum} 已经不在进行中了",
    "err.point_no_stage": "{gnum} 是点状任务，只有一个时间点，不开环节",
    "err.stage_on_done": "{gnum} 已经完成，不能再开环节",
    "err.stage_on_abandoned": "{gnum} 已经放弃，不能再开环节",
    "err.stage_open": "{gnum} 的「{stage}」环节已经在进行中（从 {since} 起）",
    "err.stage_not_open": "{gnum} 的「{stage}」环节没有在进行中",
    "err.end_before_start": "结束时间不能早于这个环节的开始",
    "err.point_complete": "{gnum} 是点状任务：做完一次用 point_done，不再做了用 goal_update status=abandoned",
    "err.already_done": "{gnum} 已经完成过了",
    "err.complete_before_stage": "完成时间早于「{stage}」环节的开始",
    "err.todo": "待办 {id} 不存在或已完成",
    "err.note": "口述 #{id} 不存在或已处理",
    "err.bad_sync_status": "status 只能是 pushed / skip",
    "err.bad_entry_ids": "entry_ids 要是记录编号列表，收到 {value}",
    "err.not_pending": "记录 {id} 不是待推状态",
    "err.void": "记录 {id} 不存在或已作废",
    "err.not_point_done": "{gnum} 不是点状任务（普通目标做完用 complete）",
    "err.point_cancelled": "{gnum} 已经取消了",
    "err.no_occurrence": "{gnum} 没有 {at} 这一次（规则：{rule}）",
    "err.none_within": "{gnum} 往后 7 天内没有还没做的一次（规则：{rule}）；要提前勾更远的那次，写 occurrence",
    "err.already_ticked": "{at} 这一次已经勾过了（记录 {id}）",
    "err.just_ticked": "{at} 这一次刚被别的对话勾过了",
    "err.day_range": "日期范围要在 93 天以内且先后顺序对",
    "err.act_shape": "action 要是字符串，params 要是对象",
    "err.request_id": "request_id 要是 16–128 字符的唯一编号（建议 UUID）；重试保持不变",
    "err.request_reused": "request_id 已用于不同操作；请读现状，不能换内容重试",

    # ---------- 写进记录里的文字 ----------
    "text.create": "立项：{title}",
    "text.stage_start": "开始「{stage}」环节",
    "text.stage_end": "结束「{stage}」环节",
    "text.stage_end_abandon": "随目标放弃结束「{stage}」环节",
    "text.stage_end_complete": "随目标完成结束「{stage}」环节",
    "text.complete": "完成",
    "text.due": "计划完成日 {old} → {new}",
    "text.unset": "未定",
    "text.reason": "：{reason}",
    "text.point_change": "改时间点：{before} → {after}",
    "text.summary_edit": "改「{label}」：{value}",
    "text.cleared": "（清空）",
    "text.semi": "；",
    "text.point_done": "做完：{title}（{at}那次）",

    # ---------- 团队看板 ----------
    "team.status.active": "进行中",
    "team.status.done": "已完成",
    "team.status.abandoned": "已放弃",
    "team.off": "没有连团队看板（配置里 team_board.base_url 为空）；个人看板单独用，不拉也不推",
    "team.demo": "现在是演示数据，不拉团队目标；换成自己的（./board reset --execute）后再拉",
    "team.bad_url": "团队看板地址要以 http:// 或 https:// 开头",
    "team.http": "团队看板回 {code}：{body}",
    "team.unreachable": "连不上团队看板 {base}：{reason}",
    "team.read_error": "读团队看板出错：{error}",
    "team.not_json": "团队看板返回的不是 JSON（可能是登录页）：{head}",
    "team.no_goals": "团队看板返回里没有 goals",
    "team.write_failed": "写入本地看板失败：{error}",
    "team.task": "团队看板",
    "team.created": "立项（团队看板上立的，拉入时补记）",
    "team.created_guess": "立项（团队看板上立的，拉入时补记；立项时刻以团队看板为准）",
    "team.stage_open": "团队看板上「{stage}」环节已在进行",
    "team.start_at_pull": "（起点以团队看板为准，这里按拉取时刻记）",
    "team.stage_closed": "团队看板上「{stage}」环节已结束",
    "team.at_pull": "（按拉取时刻记）",
    "team.marked": "团队看板已标{status}",
    "team.marked_stage": "{marked}，结束「{stage}」环节",
    "team.paused": "暂停：{kind}",
    "team.note_paused": "团队看板：{text}",
    "team.note_resumed": "团队看板：恢复（不再暂停）",
    "team.due": "团队看板上计划完成改为 {new}（原 {old}）",
    "team.no_due": "不定",
    "team.reopened": "团队看板上重新打开（改回进行中）",
    "team.not_mine": "团队看板：已不归我负责",
    "team.not_mine_note": "团队看板上这个目标已不归我负责（或已删除）；要收口就 complete / void，要留着就改负责人后再拉",
    "head.pulled_ago": "团队目标 {mins} 分钟前拉过",
    "head.pulled_at": "团队目标 {at} 拉过",
    "head.never_pulled": "团队目标从未拉过",

    # ---------- 示例里的假设案例 ----------
    "sample.task": "示例",
    "sample.e1.title": "宠物寄养预约（假设案例）",
    "sample.e1.next": "假设案例：一件大事按「一人负责到底」拆块来做会是什么样",
    "sample.e11.title": "A 预约页面",
    "sample.e11.next": "不依赖别的块，从产品一路做到测试",
    "sample.e12.title": "B 订单与排期",
    "sample.e12.next": "开发整个排在 C（别人整包的寄养门店接口）完成之后",
    "sample.e12.log_wait": "产品做完，等 C（别人整包的门店接口）——等依赖，不算开发时间",
    "sample.e12.log_go": "C 完成，开始开发",
    "sample.e11.log_back": "测出 5 个问题回头改产品，测试同时继续",
    "sample.e2.title": "App 内消息中心（假设案例）",
    "sample.e2.next": "母题：发起、业务、验收、兜底；三块拆给别人（在团队看板上）；检查点：产品方案做完我验收一次",
    "sample.e2.log": "业务说明交出去了；三块已在团队看板立项",
    "sample.e2.todo": "产品方案做完，验收一次再定开发归谁",

    # ---------- 演示数据 ----------
    "seed.bad_lang": "演示数据只有 zh 和 en 两套",
    "seed.not_empty": "库里已经有数据了，演示数据只往空库里灌（要从头来：./board reset --execute）",

    # ---------- 网页接口 ----------
    "http.no_page": "没有这个页面：{path}",
    "http.no_api": "没有这个接口",
    "http.bad_params": "参数不对：{error}",
    "http.bad_length": "Content-Length 不是数字",
    "http.not_json": "请求体不是 JSON",
    "http.sample_readonly": "示例看板只读，要试操作去练手看板",
    "http.act_format": '格式：{"action": "...", "params": {...}}',
    "http.mode_no_pull": "只有正式看板拉团队目标",
    "http.reset_practice_only": "只有练手看板能重置",

    # ---------- 命令行 ----------
    "cli.serving": "个人看板：http://127.0.0.1:{port}/ （示例 /sample/，练手 /practice/）",
    "cli.init_exists": "已经初始化过了：{path}。要重新生成配置加 --force（数据库不受影响）。",
    "cli.init_done": "已初始化：{path}\n  本人 {name}（id {id}，出生号字母 {letter}），端口 {port}，时区 {zones}\n  团队看板：{team}\n  数据库 {db}；练手库已建\n下一步：./board seed（灌演示数据，可选）→ ./board start",
    "cli.team_off": "未连接（单独使用）",
    "cli.seed_done": "演示数据已灌入 {db}：目标 {goals} 个、记录 {entries} 条；练手库已随之重建。\n看够了换成自己的：./board reset --execute",
    "cli.practice_dry": "DRY RUN：将用此刻的正式数据 + 假设案例从头重建练手库。加 --execute 执行。",
    "cli.practice_done": "已重建练手库：{path}",
    "cli.already_running": "已经在跑（pid {pid}）：http://127.0.0.1:{port}/",
    "cli.started": "已启动（pid {pid}）：http://127.0.0.1:{port}/  示例 /sample/  练手 /practice/  日志 {log}",
    "cli.start_failed_exited": "没起来（进程已退出，端口可能被占），看日志：{log}",
    "cli.start_failed_silent": "没起来（进程没响应），看日志：{log}",
    "cli.not_running": "没有在跑",
    "cli.stopped": "已停止（pid {pid}）",
    "cli.status_running": "在跑 pid {pid}  http://127.0.0.1:{port}/  数据目录 {data}",
    "cli.status_stopped": "没在跑  http://127.0.0.1:{port}/  数据目录 {data}",
    "cli.app_macos_only": "应用壳只做了 macOS 的",
    "cli.app_foreign": "{path} 已经存在，而且不是本工具生成的，不覆盖。先把它改名或移走。",
    "cli.app_dry": "DRY RUN：将生成 {path}（双击 = 起服务并在浏览器打开）。加 --execute 执行。",
    "cli.app_alert": "个人看板没起来，看日志：",
    "cli.app_done": "已生成：{path}\n  双击打开 {url}\n  可以拖到程序坞；日志 {log}",
    "cli.reset_dry": "DRY RUN：将把 {db} 备份到 {backups}/ 后清空重建（本人 {name} 不变），练手库同步重建。加 --execute 执行。",
    "cli.reset_done": "已清空：{db}；备份 {backup}；练手库已重建。",
    "cli.no_backup": "无（原来没有正式库）",
    "cli.backup_dry": "DRY RUN：将在线备份 {db}，完整性检查后保留最近 30 份。加 --execute 执行。",
    "cli.backup_bad": "备份完整性检查失败",

    # ---------- MCP ----------
    "mcp.now": "现在",
    "mcp.bad_when": "when 要写成 2026-10-02 09:30（按 zone 解释）或带时区偏移的 ISO 时间",
    "mcp.unknown_args": "{tool} 不认识的参数：{keys}",
    "mcp.missing_args": "{tool} 缺少参数：{keys}",
    "mcp.bad_type": "{tool} 的 {key} 类型不对，要 {type}",
    "mcp.no_tool": "没有这个工具：{name}",
    "mcp.no_guide": "手册不在：{path}（MCP 的 instructions 来自它，缺了不启动）",
    "mcp.bad_method": "不支持的方法：{method}",
    "mcp.actions_note": "记录（log / stage_start / stage_end）都带 task 与 tool；occurred_at 不填 = 现在",
    "mcp.pending_note": "收尾时按这个清单请人点头，再经团队看板自己的 MCP 逐条推；推完用 sync_mark 标记",
    "mcp.state": "个人看板现状：顶栏（未推几条、团队目标何时拉过）、各条线里进行中的目标（号、正在进行的环节、下一步、最后一条记录）、"
                 "某一天按小时的记录、最近 7 天、待办、口述清单、今天到点或已过期没做的点状任务（points_due）。day 不填 = 今天。只读。",
    "mcp.goal": "一个目标的详情：各环节起止与时长、全部记录按天、待办、相关对话、上层与拆出的块。只读。",
    "mcp.timeline": "一段时间内时间线上该出现的目标与环节段（进行中的 + 这段时间里有动静的）。只读。",
    "mcp.pending": "全部「未推」记录（会推到团队看板但还没推的），收尾时按这个清单请人点头。没连团队看板时为空。只读。",
    "mcp.actions": "个人看板操作说明（唯一来源）：每个操作做什么、必填 / 选填字段，以及线、环节、记录种类、工具、时区的取值表。只读。",
    "mcp.guide": "个人看板手册全文（对话一开始怎么归类、记到多细、环节把关、收尾推团队看板、口述与点状任务）。"
                 "有的客户端只显示 MCP 说明的开头一段，开始归类或记录前先读这里。只读。",
    "mcp.time": "时间换算（用时区库，别心算）：不传 when 给现在；传「2026-10-02 09:30」和 zone，返回配置的每个时区的写法、"
                "请人确认用的一行（both）和可直接填 occurred_at 的时间。只读。",
    "mcp.act": "往个人看板写一个操作（{actions}）。params 原样交给看板校验，报错原样带回。成功返回 ids / goal_id / gnum。会写。",
    "mcp.pull": "从团队看板重新拉一次本人负责的目标（只读团队看板，写个人看板的目标行）。没连团队看板或失败时原样报错。",
    "mcp.p.day": "YYYY-MM-DD（主时区的日期）",
    "mcp.p.goal": "G 号（G2.2）或出生号（{letter}19，推上团队看板后仍认）",
    "mcp.p.iso": "带时区的 ISO",
    "mcp.p.when": "2026-10-02 09:30（按 zone 解释）或带时区的 ISO；不填 = 现在",
    "mcp.p.zone": "按哪个时区解释 when：main（主时区，默认）/ second，或配置里的时区名、标签",
    "mcp.p.request_id": "建议填 UUID；结果不明要重试时沿用同一编号与参数，避免重复记录",
    "mcp.p.action": "操作说明（actions）列出的操作名",
    "mcp.p.params": "该操作的参数；补录加 occurred_at（带时区）；记录要带 task（这个对话在做的事）和 tool（claude / codex）",
    "mcp.check.data": "数据：{db}（{mode}）本人 {name}，出生号字母 {letter}",
    "mcp.check.guide": "手册：{path}（版本 {version}，{chars} 字）",
    "mcp.check.summary": "进行中目标 {goals} 个；未推 {pending} 条；团队看板：{team}",
    "mcp.check.tools": "工具：{tools}",

    # ---------- 页面模板 ----------
    "tpl.pending_tip": "会推到团队看板、但还没推的记录",
    "tpl.pending_a": "未推 ",
    "tpl.pending_b": " 条",
    "tpl.pull_tip": "从团队看板重新拉一次你负责的目标",
    "tpl.pull": "拉团队目标",
    "tpl.theme_tip": "浅色 / 深色 / 跟系统",
    "tpl.theme_light": "浅",
    "tpl.theme_dark": "深",
    "tpl.theme_auto": "自动",
    "tpl.guide": "照着做",
    "tpl.zoom_day": "一天",
    "tpl.zoom_three": "三天",
    "tpl.zoom_week": "一周",
    "tpl.earlier": "往前",
    "tpl.later": "往后",
    "tpl.back_today": "回到今天",
    "tpl.pick_tip": "点开日历跳到某天",
    "tpl.unfold_all": "全部展开",
    "tpl.fold_all": "全部收起",
    "tpl.goals": "目标",
    "tpl.hint": "拖动看别的日子 · 点日期看那天的记录 · 点线的标题收起或展开 · 悬停一个目标，它和它下面的块一起亮 · 进行中的目标从立项起一直在、往后是虚线（还在做），做完的随时间退出视野、拖回去又出现 · 点状任务（如每月结款）拖到那个时间点才出现：空心没做、实心做完，过期没做的留到今天标红",
    "tpl.order_tip": "当天记录的排法，选过会记住",
    "tpl.order_desc": "最新在上",
    "tpl.order_asc": "按时间顺序",
    "tpl.todos": "待办",
    "tpl.dictation": "口述框",
    "tpl.dictation_help": "把事情用自己的话写下来（口述或打字都行），保存后会复制一段话，粘到 AI 对话框，AI 用个人看板的接口录进去；缺什么它会先问。改东西都走这里，不填表。",
    "tpl.dictation_ph": "例如：引导页今天跑通了，下一步做回归；或：明天先把评分引导的方案写完……",
    "tpl.dictation_save": "保存并复制给 AI",
    "tpl.changelog": "更新日志",
    "tpl.stage_spans": "各环节起止",
    "tpl.entries": "记录",
    "tpl.tasks": "相关对话 / 任务",

    # ---------- 「照着做」页 ----------
    "guide.title": "照着做",
    "guide.subtitle": "照着做：把个人看板用起来",
    "guide.what.h": "这是什么",
    "guide.what.body": "<p>个人看板是你自己的实时工作台：你开的每个 AI 对话（Claude Code、Codex）一开始就被归到<b>哪条线、哪个目标、哪个环节</b>；做出看得见的结果时 AI 记一条，收尾时记一条。打开看板就知道主线上每件事到哪了、今天做了什么。数据只在你这台电脑上（sqlite，只追加、不删除）。</p>",
    "guide.start.h": "一、起自己的看板（一次）",
    "guide.start.body": "<pre>./board init --lang zh --name 你的名字 --letter 你的字母\n./board seed        # 可选：灌一份虚构的演示数据先看看\n./board start\n./board open</pre><p>线、环节、时区、语言都在数据目录的 <code>config.json</code> 里改，改完重启。看够了演示数据：<code>./board reset --execute</code>（先备份再清空）。电脑重启后再 <code>./board start</code> 一次即可。</p>",
    "guide.ai.h": "二、把 AI 接上（一次）",
    "guide.ai.body": "<p>Claude Code（用户级注册，所有目录都能用）：</p><pre>claude mcp add -s user personal-board -- python3 /你的路径/personal-board/cli/mcp.py</pre><p>Codex：在 <code>~/.codex/config.toml</code> 加一段：</p><pre>[mcp_servers.personal-board]\ncommand = \"python3\"\nargs = [\"/你的路径/personal-board/cli/mcp.py\"]</pre><p>接上以后，AI 会按随通道带去的手册做事，不用你贴。</p>",
    "guide.daily.h": "三、每天怎么用",
    "guide.daily.body": "<ul><li><b>开工</b>：对 AI 说「开工」，它读看板列出今天在推的目标和下一步；先做哪件你当场定。</li><li><b>随手记</b>：在任一对话里做事，AI 自己记开工、结果、收尾；要进一个新环节时它会先问你。</li><li><b>口述框</b>：想改什么、补什么，写在看板的口述框里保存，粘给 AI；不填表。</li><li><b>点状任务</b>：只在某个时间点做一次的事（例：每月 1 号给外包结款），对 AI 说一句就建好；时间线上到那一刻才出现一个空心大点，做完说一声变实心，过期没做的留到今天标红。到期那天第一个开工的对话会提醒一次。</li><li><b>收尾</b>：说「收工」，AI 汇总今天；连了团队看板的话，它列出「未推」的几条，你点头后推上去。</li><li><b>示例 / 练手</b>：顶栏切「示例」看正式数据的实时镜像加两个假设案例（只读）；切「练手」随便操作、随时「重置练手数据」，和正式数据完全分开。</li></ul>",
    "guide.team.h": "四、连团队看板（可选）",
    "guide.team.body": "<p>不配就是完全关闭：不拉、不推、页面上没有任何相关提示。要连，在 <code>config.json</code> 的 <code>team_board</code> 里填 <code>base_url</code> 和 <code>token</code>（或用环境变量 <code>PERSONAL_BOARD_TEAM_TOKEN</code>）。之后团队线上的立项、环节起止、改期、完成会带「未推」标记；收尾时你点头，AI 经团队看板自己的 MCP 批量推上去。个人线永远不推。</p>",

    # ---------- 浏览器里的文字（js.*） ----------
    "js.app_name": "个人看板",
    "js.sep": "、",
    "js.paren": "（{x}）",
    "js.today": "今天",
    "js.wd_mon": "周一", "js.wd_tue": "周二", "js.wd_wed": "周三", "js.wd_thu": "周四", "js.wd_fri": "周五", "js.wd_sat": "周六", "js.wd_sun": "周日",
    "js.cal_wd": "一,二,三,四,五,六,日",
    "js.cal_entries": "{n} 条记录",
    "js.cal_prev": "上个月",
    "js.cal_next": "下个月",
    "js.cal_month": "{y} 年 {m} 月",
    "js.cal_hint": "有点的日子有记录",
    "js.st_active": "进行中",
    "js.st_done": "已完成",
    "js.st_abandoned": "已放弃",
    "js.no_stage": "未分环节",
    "js.digest": "沉淀",
    "js.backfilled": "补录",
    "js.hours": "{n} 小时",
    "js.late_hours": "{n} 小时",
    "js.late_days": "{n} 天",
    "js.late": "延期 {late}",
    "js.late_done": "完成时延期 {late}",
    "js.overdue": "过期 {late}",
    "js.overdue_done": "完成时过期 {late}",
    "js.missed_total": "（共 {n} 次没做）",
    "js.missed_n": "有 {n} 次没做",
    "js.cancelled": "已取消",
    "js.occ_done": "做完",
    "js.occ_overdue": "过期没做",
    "js.occ_upcoming": "还没到",
    "js.occ_cancelled": "取消前没做",
    "js.team_number": "团队看板上的号",
    "js.next_is": "下一步：{text}",
    "js.unfold_blocks": "展开下面的块",
    "js.fold_blocks": "收起下面的块",
    "js.blocks_folded": "收起 {n} 块",
    "js.blocks_n": "{n} 块",
    "js.open_inside": "里面在进行",
    "js.stage_of": "{stage} 环节",
    "js.started": "开始 {at}",
    "js.plan_at": "计划 {at}",
    "js.moved_to": "改到 {at}",
    "js.items_folded": "收起 {n} 项",
    "js.items_n": "{n} 项",
    "js.none_here": "这段时间没有",
    "js.moved_notice": "拖到了 {day} 这段：",
    "js.rows_in": "出现 {n} 项这段时间有动静的",
    "js.rows_out": "{n} 项这段时间没动静的退出",
    "js.leg_going": "还在做",
    "js.leg_entry": "记录",
    "js.leg_point": "点状任务没做",
    "js.pull_failed": "团队目标拉取失败：{error}",
    "js.pull_error": "没拉到：{error}",
    "js.pulling": "拉取中…",
    "js.mode_sample": "示例看板",
    "js.mode_practice": "练手看板",
    "js.note_demo": "演示数据：这是一家虚构的小团队（做宠物照护 App）的看板，拿来看看个人看板用起来是什么样；数据只在这台电脑上。看够了换成自己的：终端跑 <code>./board reset --execute</code>（会先备份）。",
    "js.note_sample": "示例看板：正式看板的<b>实时镜像</b>（真实目标与记录和正式页同步，不会漂移），加上两个假设案例，演示一件大事拆块来做是什么样。<b>只读</b>，要试操作去练手看板。",
    "js.note_practice": "练手看板：随便操作、学着用，这里的记录<b>不是真的</b>、不会推到团队看板。玩乱了点 {button}（恢复成此刻的正式数据 + 假设案例）。AI 要连练手数据：启动 MCP 时设 PERSONAL_BOARD_PRACTICE=1。",
    "js.reset_practice": "重置练手数据",
    "js.reset_confirm": "把练手数据恢复成此刻的正式数据 + 假设案例？",
    "js.day_title": "{day} 的记录（{n} 条）",
    "js.pick_date": "选日期",
    "js.no_todos": "没有待办",
    "js.notes_done": "已处理 {n} 条",
    "js.empty_day": "这天还没有记录。在任一 AI 对话里做事，AI 会把结果记到这里。",
    "js.note_n": "口述 #{id}",
    "js.note_about": "关于 {gnum}",
    "js.note_resolved": "已处理 {at}：{summary}",
    "js.copy_to_ai": "复制给 AI",
    "js.pending_title": "未推到团队看板的记录（{n} 条）",
    "js.pending_none": "没有未推的记录",
    "js.pending_help": "收尾时对 AI 说「收工」，它会把这些列给你点头，然后推到团队看板。",
    "js.back_to_day": "回到当天记录",
    "js.dictation_prompt": "请把下面这段口述录进我的个人看板（口述 #{id}）。按个人看板手册：先看看板现状，对到目标和环节；缺信息先问我，不要猜；录完把口述 #{id} 标记为已处理，并告诉我记了什么。",
    "js.copy_fallback": "浏览器没让自动复制：下面这段已选中，按 ⌘C / Ctrl+C 复制。",
    "js.copied": "口述 #{id} 已复制，粘到 AI 对话框即可。",
    "js.write_first": "先写点内容",
    "js.save_failed": "没保存成功：{error}",
    "js.long_term": "长期",
    "js.pending_n": "未推 {n} 条",
    "js.what": "做什么",
    "js.done_what": "做了什么",
    "js.why_abandoned": "为什么放弃",
    "js.next": "下一步",
    "js.blocker": "卡点",
    "js.moment": "时间点",
    "js.next_occ": "；下一次 {at}",
    "js.point_note": "；点状任务，不推团队看板",
    "js.point_note_solo": "；点状任务",
    "js.open_stages": "正在进行的环节",
    "js.source": "来源",
    "js.src_pushed": "个人看板立项，已推到团队看板",
    "js.src_team": "团队看板（本人负责）",
    "js.src_local": "个人看板立项",
    "js.birth": "出生号",
    "js.birth_pushed": "（推上团队看板后显示 {gnum}，用 {birth} 两边都能找到）",
    "js.birth_note": "；提交信息里写这个号",
    "js.created": "立项",
    "js.plan": "计划 {due}",
    "js.plan_unset": "计划未定",
    "js.plan_was": "（原定 {due}）",
    "js.belongs": "属于",
    "js.blocks": "拆出的块",
    "js.block_done": "（已完成）",
    "js.occurrences": "每一次",
    "js.th_moment": "时刻",
    "js.th_done": "做没做",
    "js.th_stage": "环节",
    "js.th_start": "开始",
    "js.th_end": "结束",
    "js.th_hours": "时长",
    "js.no_stages": "没有分环节",
    "js.no_entries": "还没有记录",
    "js.no_tasks": "还没有对话记过这个目标",

    # ---------- 样例包 ----------
    "case.unreadable": "读不了样例包 {path}：{error}",
    "case.bad_format": "不是个人看板样例包（format 应为 1，且要有 tables）",
    "case.bad_rows": "样例包里有灌不进去的行，什么都没写入：{error}",
    "case.not_empty": "库里已经有数据了，样例包只往空库里灌（要从头来：./board reset --execute）",
    "case.no_config": "这份样例包里没有线或环节可照搬；不加 --adopt-config 也能灌",
    "case.someone": "别人",
    "case.label": "{who}的看板副本（{at} 导出）",
    "case.label_undated": "{who}的看板副本",
    "case.no_push": "样例数据，不从这里推团队看板",
    "team.case": "现在是样例包里的数据，不拉团队目标；换成自己的（./board reset --execute）后再拉",
    "cli.case_done": "已灌入{label}到 {db}：目标 {goals} 个、记录 {entries} 条、待办 {todos} 条；未推的已标「不推」，练手库已随之重建。\n看够了换成自己的：./board reset --execute",
    "cli.case_missing": "提示：样例包里有你配置里没有的名字（线：{lines}；环节：{stages}），页面上照样显示（线排在最后）。想让它们按样例包原来的顺序和配色显示，reset 后重灌时加 --adopt-config。",
    "cli.case_adopted": "已把样例包的线和环节写进配置。",
    "cli.export_done": "已导出：{path}（目标 {goals} 个、记录 {entries} 条、待办 {todos} 条；口述不导）。别人用 ./board seed --case 这个文件 就能灌进空库。",
    "cli.none": "无",
    "js.note_case": "样例数据：这是<b>{label}</b>，拿来照着看个人看板怎么用；数据只在这台电脑上、不会推到团队看板。看够了换成自己的：终端跑 <code>./board reset --execute</code>（会先备份）。",
}
